name: template_flutter
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  graphql_flutter: ^5.1.0
  graphql: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.14.0+1

flutter:
  uses-material-design: true
